import { ProjectClient, ProjectItem } from './project.js';
import * as core from '@actions/core';

export interface Sprint {
  name: string;
  iterationId: string;
  startDate: Date;
  endDate: Date;
  goal: string;
}

export function getCurrentSprint(items: ProjectItem[]): Sprint | null {
  // Find items with Sprint field value
  for (const item of items) {
    const sprintValue = item.fieldValues['Sprint'];
    if (sprintValue && typeof sprintValue === 'string') {
      // Extract sprint info from field
      // In real implementation, this would parse iteration metadata
      return {
        name: sprintValue,
        iterationId: 'current',
        startDate: new Date(),
        endDate: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000),
        goal: (item.fieldValues['Sprint Goal'] as string) || '',
      };
    }
  }
  return null;
}

export function isSprintEnded(sprint: Sprint): boolean {
  const now = new Date();
  return now > sprint.endDate;
}

export function generateSprintStartSummary(
  sprintName: string,
  goal: string,
  capacity: number,
  totalIssues: number,
  passedDoR: number,
  failedDoR: number
): string {
  const lines: string[] = [];
  
  lines.push(`## 🚀 Sprint Started: ${sprintName}`);
  lines.push('');
  lines.push(`**Goal:** ${goal}`);
  lines.push('');
  lines.push('### Capacity');
  lines.push('');
  lines.push(`- **Total Capacity:** ${capacity} story points`);
  lines.push(`- **Issues Committed:** ${totalIssues}`);
  lines.push('');
  lines.push('### Definition of Ready');
  lines.push('');
  lines.push(`- ✅ Passed: ${passedDoR} issues`);
  
  if (failedDoR > 0) {
    lines.push(`- ⚠️ Needs Refinement: ${failedDoR} issues`);
    lines.push('');
    lines.push('> Issues failing DoR have been commented with specific requirements.');
  } else {
    lines.push('');
    lines.push('> All issues meet the Definition of Ready!');
  }
  
  lines.push('');
  lines.push('---');
  lines.push('');
  lines.push('Good luck with the sprint! 🎯');
  
  return lines.join('\n');
}

export function generateRetrospectiveTemplate(
  sprintName: string,
  goal: string,
  metrics: {
    planned: { issues: number; points: number };
    completed: { issues: number; points: number };
    carryover: { issues: number; points: number };
  }
): string {
  const lines: string[] = [];
  
  lines.push(`## Retrospective: ${sprintName}`);
  lines.push('');
  lines.push(`**Sprint Goal:** ${goal || 'Not set'}`);
  lines.push('');
  lines.push('## What went well?');
  lines.push('- ');
  lines.push('');
  lines.push('## What could be improved?');
  lines.push('- ');
  lines.push('');
  lines.push('## Action items for next sprint');
  lines.push('- [ ] ');
  lines.push('');
  lines.push('## Metrics');
  lines.push('');
  lines.push(`- **Planned:** ${metrics.planned.issues} issues (${metrics.planned.points} pts)`);
  lines.push(`- **Completed:** ${metrics.completed.issues} issues (${metrics.completed.points} pts)`);
  lines.push(`- **Carried over:** ${metrics.carryover.issues} issues (${metrics.carryover.points} pts)`);
  lines.push(`- **Sprint Goal met:** ${metrics.completed.issues === metrics.planned.issues ? 'Yes' : 'No'}`);
  lines.push('');
  lines.push('---');
  lines.push('');
  lines.push('*Generated by GitHub Scrum automation*');
  
  return lines.join('\n');
}

export function calculateSprintDates(days: number): { startDate: Date; endDate: Date } {
  const startDate = new Date();
  // Start on Monday
  const dayOfWeek = startDate.getDay();
  const daysUntilMonday = (8 - dayOfWeek) % 7 || 7;
  startDate.setDate(startDate.getDate() + daysUntilMonday);
  startDate.setHours(0, 0, 0, 0);
  
  const endDate = new Date(startDate);
  endDate.setDate(endDate.getDate() + days);
  
  return { startDate, endDate };
}
